export default [
   {
      id: 0,
      name: 'H&M Cutton Polo Shirt Brown',
      price: 5.95,
      symbol: '$',
      reviews: 6500,
      totalStocks: 12,
      imagePathName: '1.jpg',
   },
   {
      id: 1,
      name: 'Winter Suit',
      price: 7.22,
      symbol: '$',
      reviews: 4200,
      totalStocks: 9,
      imagePathName: '2.jpg',
   },
   {
      id: 2,
      name: 'H&M Straight Denim Short',
      price: 3.59,
      symbol: '$',
      reviews: 8500,
      totalStocks: 4,
      imagePathName: '3.jpg',
   },
   {
      id: 3,
      name: 'Blue Jeans Bag For Travel',
      price: 2.45,
      symbol: '$',
      reviews: 9600,
      totalStocks: 3,
      imagePathName: '4.jpg',
   },
   {
      id: 4,
      name: 'Leather Wallet Brown Lacoste',
      price: 29.99,
      symbol: '$',
      reviews: 5111,
      totalStocks: 6,
      imagePathName: '5.jpg',
   },
   {
      id: 5,
      name: 'Amazing Sofa',
      price: 53.95,
      symbol: '$',
      reviews: 4500,
      totalStocks: 2,
      imagePathName: '6.jpg',
   },
   {
      id: 6,
      name: 'Apple SmartWatch Black',
      price: 25.99,
      symbol: '$',
      reviews: 5650,
      totalStocks: 9,
      imagePathName: '7.jpg',
   },
   {
      id: 7,
      name: 'Apple AirPod',
      price: 55.99,
      symbol: '$',
      reviews: 2954,
      totalStocks: 3,
      imagePathName: '8.jpg',
   },
   {
      id: 8,
      name: 'Bose Headphones 700',
      price: 30.99,
      symbol: '$',
      reviews: 5501,
      totalStocks: 6,
      imagePathName: '9.jpg',
   },
   {
      id: 9,
      name: 'Ecobee Mifi',
      price: 31.99,
      symbol: '$',
      reviews: 7868,
      totalStocks: 3,
      imagePathName: '10.jpg',
   }
]